#!/bin/bash

set -e
if [ -z $1 ]; then
   VER="2.0.0"
else
   VER=$1
fi

docker rm -f superset_app

docker build --tag data-diving/superset-xlsx --build-arg SUPERSET_VER=$VER .
docker run --rm -d -p 8088:8088 --name superset_app --platform linux/AMD64 data-diving/superset-xlsx
docker exec superset_app superset fab create-admin \
   --username admin \
   --firstname Admin \
   --lastname Admin \
   --email admin@superset.com \
   --password admin
docker exec superset_app superset db upgrade
docker exec superset_app superset load_examples
docker exec superset_app superset init

echo "http://localhost:8088 (admin/admin)"




