#!/bin/bash

set -e
if [ -z $1 ]; then
   VER="2.0.0"
else
   VER=$1
fi

docker build --tag babonito/superset-xlsx --build-arg SUPERSET_VER=$VER .
docker run --rm -d -p 8088:8088 --name babonito --platform linux/AMD64 babonito/superset-xlsx
docker exec babonito superset fab create-admin \
   --username admin \
   --firstname Admin \
   --lastname Admin \
   --email admin@superset.com \
   --password admin
docker exec babonito superset db upgrade
docker exec babonito superset init
echo "http://localhost:8088 (admin/admin)"




